config/routes.rb
Rails.application.routes.default_url_options = {
	host: 'https://sayna-madagascar.herokuapp.com'
}
Rails.application.routes.draw do
  resources :conversations
  resources :messages
  ## Guest available links
  get '/acceuil', to: "pages#home",                   as: "acceuil"
  get '/àpropos', to: "pages#about",                  as: "apropos"
  get '/équipe', to: "pages#team",                    as: "equipe"
  get '/contact', to: "pages#contact",                as: "contact"
  
  ## Connected users
  get '/mon-dashboard', to: "pages#dashboard",        as: "mon_dashboard"
  get '/mon-profil', to: "users#show",                as: "mon_profil"
  get '/editer-mon-profil', to: "users#edit",         as: "editer_mon_profil"
  patch '/editer-mon-profil', to: "users#update"

  get '/mes-conversations', to: "conversations#index",as: "mes_conversations"
  get '/conversation/:id', to: "conversations#show"
  
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks",
    passwords: "users/passwords"
  }

  devise_scope :user do
    get "/connexion", to: "users/sessions#new",            as: "connexion"
    delete "/déconnexion", to: "users/sessions#destroy",   as: "deconnexion"
    get "/inscription", to: "users/registrations#new",     as: "inscription"
    post "/inscription", to: "users/registrations#create", as: "post_inscription"
  end

  resources :users

  ## Staff available links
  get "/tous-les-étudiants", to: "users#index", as: "tous_les_etudiants"
  get "/rechercher", to: "searches#new", as: "rechercher"
  post "/rechercher", to: "searches#create", as: "post_rechercher"

  root to: "pages#home"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :users
  has_many :messages, through: :members
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]
  layout 'conversations'
  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.all
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:user_id, :name)
    end

    def authenticate_user
      authenticate_user!
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, local: true) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<div class="jumbotron text-center mt-3 mx-0 mb-0">
    Page conversations index
</div>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<div class="jumbotron text-center mt-3 mx-0 mb-0">
    <p>
        <strong>Créée par:</strong>
        <%= @conversation.user.username %>
    </p>
    <p>
        <strong>Nom du groupe:</strong>
        <%= @conversation.name %>
    </p>
</div>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		
	});
</script>