config/routes.rb
Rails.application.routes.default_url_options = {
	host: 'https://sayna-madagascar.herokuapp.com'
}
Rails.application.routes.draw do
  resources :conversations
  resources :messages
  ## Guest available links
  get '/acceuil', to: "pages#home",                   as: "acceuil"
  get '/àpropos', to: "pages#about",                  as: "apropos"
  get '/équipe', to: "pages#team",                    as: "equipe"
  get '/contact', to: "pages#contact",                as: "contact"
  
  ## Connected users
  get '/mon-dashboard', to: "pages#dashboard",        as: "mon_dashboard"
  get '/mon-profil', to: "users#show",                as: "mon_profil"
  get '/editer-mon-profil', to: "users#edit",         as: "editer_mon_profil"
  patch '/editer-mon-profil', to: "users#update"

  get '/mes-conversations', to: "conversations#index",as: "mes_conversations"
  get '/conversation/:id', to: "conversations#show"
  
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks",
    passwords: "users/passwords"
  }

  devise_scope :user do
    get "/connexion", to: "users/sessions#new",            as: "connexion"
    delete "/déconnexion", to: "users/sessions#destroy",   as: "deconnexion"
    get "/inscription", to: "users/registrations#new",     as: "inscription"
    post "/inscription", to: "users/registrations#create", as: "post_inscription"
  end

  resources :users

  ## Staff available links
  get "/tous-les-étudiants", to: "users#index", as: "tous_les_etudiants"
  get "/rechercher", to: "searches#new", as: "rechercher"
  post "/rechercher", to: "searches#create", as: "post_rechercher"

  root to: "pages#home"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_flash.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>" role="alert">
    <%= value %>
</div>
<% end %>

app/views/pages/_navbar.html.erb
<nav class="navbar-header navbar navbar-fixed">
    <ul class="list-group">
        <% if user_signed_in? %>
        <li class="list-group-item show index conversations">
            <a href="<%= mes_conversations_path %>">
                <%= fa_icon "wechat 4x" %></a>
        </li>
        <li class="list-group-item dashboard">
            <a href="<%= mon_dashboard_path %>">
                <%= fa_icon "dashboard 4x" %></a>
        </li>
        <li class="list-group-item sessions destroy">
            <a href="<%= deconnexion_path %>" data-method="DELETE">
                <%= fa_icon "sign-out 4x" %></a>
        </li>
        <% else %>
        <li class="list-group-item sessions new">
            <a href="<%= connexion_path %>">
                <%= fa_icon "sign-in 4x" %></a>
        </li>
        <% end %>
        <% if controller_name != "conversations" %>
        <li class="list-group-item searches new">
            <a href="<%= rechercher_path %>" id="start-search-btn">
                <%= fa_icon "search 4x" %></a>
        </li>
        <% end %>
        <li class="list-group-item home">
            <a href="<%= acceuil_path %>">
                <%= fa_icon "home 4x" %></a>
        </li>
        <li class="list-group-item contact">
            <a href="<%= contact_path %>">
                <%= fa_icon "phone 4x" %></a>
        </li>
        <li class="list-group-item team">
            <a href="<%= equipe_path %>">
                <%= fa_icon "users 4x" %></a>
        </li>
        <li class="list-group-item about">
            <a href="<%= apropos_path %>">
                <%= fa_icon "info-circle 4x" %></a>
        </li>
    </ul>
</nav>
<script type="text/javascript">
jQuery(document).ready(function($) {
    $lists = $(`.navbar li`);
    $body = $(`body`);
    for (var i = 0; i < $lists.length; i++) {
        $list = $lists.eq(i);
        $controller_name = $body.attr('class').split(" ")[0];
        $action_name = $body.attr('class').split(" ")[1];
        if ($list.hasClass($action_name)) {
            $list.addClass('active');
        }
    }
});
</script>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/dashboard.html.erb
<h1>Pages#mon-dashboard</h1>
<p>Find me in app/views/pages/dashboard.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/team.html.erb
<h1>Pages#team</h1>
<p>Find me in app/views/pages/team.html.erb</p>