config/routes.rb
Rails.application.routes.default_url_options = {
	host: 'https://sayna-madagascar.herokuapp.com'
}
Rails.application.routes.draw do
  resources :conversations
  resources :messages
  ## Guest available links
  get '/acceuil', to: "pages#home",                   as: "acceuil"
  get '/àpropos', to: "pages#about",                  as: "apropos"
  get '/équipe', to: "pages#team",                    as: "equipe"
  get '/contact', to: "pages#contact",                as: "contact"
  
  ## Connected users
  get '/mon-dashboard', to: "pages#dashboard",        as: "mon_dashboard"
  get '/mon-profil', to: "users#show",                as: "mon_profil"
  get '/editer-mon-profil', to: "users#edit",         as: "editer_mon_profil"
  patch '/editer-mon-profil', to: "users#update"

  get '/mes-conversations', to: "conversations#index",as: "mes_conversations"
  get '/conversation/:id', to: "conversations#show"
  
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks",
    passwords: "users/passwords"
  }

  devise_scope :user do
    get "/connexion", to: "users/sessions#new",            as: "connexion"
    delete "/déconnexion", to: "users/sessions#destroy",   as: "deconnexion"
    get "/inscription", to: "users/registrations#new",     as: "inscription"
    post "/inscription", to: "users/registrations#create", as: "post_inscription"
  end

  resources :users

  ## Staff available links
  get "/tous-les-étudiants", to: "users#index", as: "tous_les_etudiants"
  get "/rechercher", to: "searches#new", as: "rechercher"
  post "/rechercher", to: "searches#create", as: "post_rechercher"

  root to: "pages#home"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
  end

  def create
  	@search = params[:search][:name].to_s
    @type = params[:search][:type].to_s
  	@searches = []
    if @type == "users"
    	User.all.each do |user|
    		@searches << user if @search != "" && (user.username.include?(@search) || user.firstname.include?(@search) || user.lastname.include?(@search))
      end

    elsif @type == "conversations"
      Conversation.all.each do |conversation|
        @searches << conversation if @search != "" && (conversation.name.include?(@search))
      end
      
    end

  	respond_to do |format|
  		format.html
  		format.js
  	end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/create.html.erb
<h1>Searches#create</h1>
<p>Find me in app/views/searches/create.html.erb</p>
<% if @searches.any? %>
<ul>
    <% @searches.each do |user| %>
    <li>
        <h3>
            <%= user.username %>
        </h3>
        <ol>
            <li>
                <%= user.firstname %>
            </li>
            <li>
                <%= user.lastname %>
            </li>
            <li>
                <%= user.birthdate %>
            </li>
        </ol>
    </li>
    <% end %>
</ul>
<% else %>
<p>Aucun résultat</p>
<% end %>

app/views/searches/create.js.erb
$resultDiv.html(`
<% if @type == "users" %>
    <% if @searches.any? %>
    <div class="jumbotron text-center p-0 my-0">
        <table class="table table-active">
            <thead class="table table-dark table-bordered">
                <tr>
                    <th>Pseudo</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Heure de décès</th>
                </tr>
            </thead>
            <% @searches.each do |user| %>
            <tr class="table table-success">
                <td>
                    <%= user.username %>
                </td>
                <td>
                    <%= user.firstname %>
                </td>
                <td>
                    <%= user.lastname %>
                </td>
                <td>
                    <%= user.birthdate %>
                </td>
            </tr>
            <% end %>
        </table>
    </div>
    <% else %>
    <mark class="mx-1">aucun résultat</mark>
    <% end %>
<% else %>
    <% if @searches.any? %>
    <ul class="list-unstyled px-1 conversation-list">
        <% @searches.each do |conversation| %>
        <li>
            <%= link_to conversation_path(conversation.id), class: "text-white" do %>
            <%= fa_icon "user-circle 2x" %>
            <% end %>
            <%= conversation.name %>
        </li>
        <% end %>
    </ul>
    <% else %>
    <mark class="mx-1">aucun résultat</mark>
    <% end %>
<% end %>
`);
search();

app/views/searches/new.html.erb
<% if controller_name != "conversations" %>
<div class="container">
    <%= form_with(url: "/rechercher", html: {id: "search-form"}) do |f| %>
    <div class="form-inline">
        <%= f.text_field :'search[name]', id: "search-input", class: "form-control" %>
        <span id="search-btn" class="">
            <%= fa_icon "search 2x" %>
        </span>
    </div>
    <% end %>
    <div data-target="searches-result" class="w-100"></div>
</div>
<% else %>
<%= form_with(url: "/rechercher", html: {id: "search-form"}) do |f| %>
<div class="form-inline">
    <%= f.text_field :'search[name]', id: "search-conversations-input", class: "p-1 form-control" %>
    <span id="search-btn" class="">
        <%= fa_icon "search 2x" %>
    </span>
</div>
<% end %>
<div data-target="searches-result" class="w-100"></div>
<% end %>